apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount-trustee.yaml
  - deployment-trustee.yaml
  - service-trustee-admin.yaml
  - service-trustee-guest.yaml
  - networkpolicy-default-deny.yaml
  - networkpolicy-allow-dns.yaml
  - networkpolicy-allow-https-egress.yaml
  - networkpolicy-allow-provisioner.yaml
  - networkpolicy-allow-public-gateway.yaml
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: ocl-managed-trustee
