apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: trustee-qualification
  namespace: doppler-operator-system
spec:
  config: REPLACE_ME
  managedSecret:
    name: trustee-runtime
    namespace: trustee-system
    type: Opaque
  project: REPLACE_ME
  tokenSecret:
    name: trustee-qualification-token-secret
  verifyTLS: true
