apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backendtlspolicy-trustee.yaml
  - certificate-trustee-public.yaml
  - gateway-trustee-public.yaml
  - httproute-trustee-guest.yaml
